services:
  api:
    image: python:3.11-slim
    container_name: api-container
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - BEARER_TOKEN=${BEARER_TOKEN}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    build:
      context: .
      dockerfile: Dockerfile